from django.conf.urls import url

from . import views

urlpatterns = [
	#url(r'^$', views.index, name='index'),
	url(r'^sidebar/$', views.sidebar, name='sidebar'),
	url(r'^sidebargroup/$', views.sidebargroup, name='sidebargroup'),
	url(r'^regist/$', views.regist, name='regist'),
	url(r'^userlogin/$', views.userlogin, name='userlogin'),
	url(r'^userlogout/$', views.userlogout, name='userlogout'),
	url(r'^selectlist/$', views.selectlist, name='selectlist'),
	url(r'^submitpublishdata/$', views.submitpublishdata, name='submitpublishdata'),
	url(r'^getpublishdata/$', views.getpublishdata, name='getpublishdata'),
	url(r'^gethostverdata/$', views.gethostverdata, name='gethostverdata'),
	url(r'^getsearchchanneldata/$', views.getsearchchanneldata, name='getsearchchanneldata'),
	url(r'^getsearchplugindata/$', views.getsearchplugindata, name='getsearchplugindata'),
	url(r'^getsearchpackagedata/$', views.getsearchpackagedata, name='getsearchpackagedata'),
	url(r'^getsearchhostdata/$', views.getsearchhostdata, name='getsearchhostdata'),
	url(r'^searchchannel/$', views.searchchannel, name='searchchannel'),
	url(r'^searchplugin/$', views.searchplugin, name='searchplugin'),
	url(r'^searchpackage/$', views.searchpackage, name='searchpackage'),
	url(r'^searchhostver/$', views.searchhostver, name='searchhostver'),
	url(r'^addchannel/$', views.addchannel, name='addchannel'),
	url(r'^addhostver/$', views.addhostver, name='addhostver'),
	url(r'^pluginsearch/channelchange/$', views.ps_channelchange, name='ps_channelchange'),
	url(r'^packagesearch/channelchange/$', views.apks_channelchange, name='apks_channelchange'),
	url(r'^hostversearch/channelchange/$', views.hs_channelchange, name='hs_channelchange'),
	url(r'^getpublishdetailbyid/$', views.getpublishdetailbyid, name='getpublishdetailbyid'),
	url(r'^synchannelrecord/$', views.synchannelrecord, name='synchannelrecord'),
	url(r'^getchannellist/$', views.getchannellist, name='getchannellist'),
	url(r'^addrecord/$', views.addrecord, name='addrecord'),
	url(r'^editrecordbyid/$', views.editrecordbyid, name='editrecordbyid'),
	url(r'^saverecordbyid/$', views.saverecordbyid, name='saverecordbyid'),
	url(r'^deleterecordbyid/$', views.deleterecordbyid, name='deleterecordbyid'),
	url(r'^searchtext/$', views.searchtext, name='searchtext'),
	url(r'^islogin/$', views.islogin, name='islogin'),
	url(r'^savechannelbyid/$', views.savechannelbyid, name='savechannelbyid'),
]